Review request for JavaScript restaurant application
chrystalme/RestaurantApp pull request #1
Opened 2021-05-03 17:04 UTC by chrystalme

# Restaurant App
- Use web-pack as a bundle framework
- Create module for various functions
- import module to /src/index.js

2021-05-03 18:54 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @chrystalme  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented all of the requirements so carefully, keep it up, and your project is really almost done.
:+1: Almost all of the requirements are implemented :heavy_check_mark: 
:+1: The design is very good :heavy_check_mark: 
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Files not related to the project should not be committed and added to .gitignore (e.g. `.DS_Store`) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/gitignore.png) from Pathwright)
- [ ] The content of each page should be in its own module, kindly work on it
- [ ] The logic of tab switching should be in index.js file, this will help you to have DRY codes, don't repeat yourself
# [Optional changes] :yellow_circle: 
- [ ] Inorder to make your repository professional, you need to fix all of the issues I pointed out in my inline comments on your readme file, kindly check them out and fix every single issue
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2021-05-03 18:54 UTC, descholar-ceo commented on README.md
> +## Live Link
[optional] Since this link is not available, It would be better if you remove this `Live Link` title

2021-05-03 18:54 UTC, descholar-ceo commented on README.md
> +- [Microverse](https://microverse.com)
[optional] This link is broken, I think it should be `https://microverse.org` instead of ~`https://microverse.com`~

2021-05-03 18:54 UTC, descholar-ceo commented on README.md
> +- LinkedIn: [Malieze Afam Ifeanyi(chrys)](https://linkedin.com/afam-chrys)
[optional] This linkedin link is broken, please fix it

2021-05-03 18:54 UTC, descholar-ceo commented on README.md
> +```
[Optional] Please clarify what to do after running `npm install`

2021-05-03 18:54 UTC, descholar-ceo commented on src/page_load.js
> +      </footer>`;
- [ ] [required] Please use `document.createElement` and `document.appendChild` to create and append HTML elements to the `<div>` with `id=content`. This is an opportunity for you to practice/explore building HTML elements using only javascript. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/restaurant_page/append_requirement.png) from [Odin](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page))

2021-05-04 17:27 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @chrystalme :wave:

_I must commend your efforts so far in this project. Most of the required changes have been implemented._

__However, an outstanding change is still required before this project can be approved. Please check my comment(s) below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

- [ ] The `DS_Store` file is still available in your commit history. Kindly remove it as recommended by the last reviewer.


* * *
**Please make the required changes and submit another review request when you are done.**

**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review unless it is requested otherwise.**

**Always post your inquiries and questions on this PR thread as a comment. You can mention me (@teekaytech) so I can see your comments and respond.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-05-04 17:41 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations @chrystalme :tada: :clinking_glasses: 

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**


Do not forget to fill the project completion form, as this is important for your weekly progress score.

**_Good luck with your next task._**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

2021-05-04 17:47 UTC, merged